# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Changwoo Hacks
email: cwryu AT debian DOT org
description: > # this means to ignore newlines until "baseurl:"
  Hack n. : A non-obvious solution to an interesting problem
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://changwoo.xyz" # the base hostname & protocol for your site
#twitter_username: changwoo
#github_username:  changwoo

tag_page_layout: tag_page
tag_page_dir: tag

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

disqus: changwoo-hacks

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
